exit 1

diff --git a/.github/workflows/production_deploy.yml b/.github/workflows/production_deploy.yml
--- a/.github/workflows/production_deploy.yml
+++ b/.github/workflows/production_deploy.yml
@@ -33,7 +33,7 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - name: Failure step
-        run: echo "Staging deploy failed."
+        run: echo "Staging deploy failed." && exit 1
   generate_release_tag:
     runs-on: ubuntu-latest
     needs: [on-success]
